{% extends 'layouts/app.phtml' %}

{% block content %}
    <div class="container fluid">
        <div class="row">
            <div class="col-sm-8 mx-auto">
                <h3 class="mb-4 mt-3 text-center">New Post</h3>
                <form action="{{ path_for('posts#create') }}" method="post">
                    {{ include('layouts/_form.phtml') }}
                    <div class="form-group">
                        <button class="btn btn-block btn-primary" type="submit" value="create">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
